server:
  port: 9999
  context-path: /cmfz_wjm
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cmfz?autoReconnect=true&initialTimeout=3&useUnicode=true&characterEncoding=UTF-8
    name: cmfz
    username: root
    password: 123456
  mvc:
    view:
      suffix: .jsp
      prefix: /
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  application:
    name: kingboy-springboot-file
    #解决中文乱码
    http:
      encoding:
        charset: UTF-8
        force: true
      multipart:
        enabled: true
        max-file-size: 100000000MB
        max-request-size: 100000000MB
mybatis:
  mapper-locations: classpath:/com/baizhi/mapper/*DaoMapper.xml


